title: My Public Notes
description: Personal notes on AI, Leadership, and Parenting
theme: jekyll-theme-minimal
baseurl: "/my-public-notes"

# Exclude files from being published
exclude:
  - .gitignore
  - .cursorindexingignore
  - .specstory/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Enable GitHub Flavored Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections for different categories
collections:
  ai:
    output: true
    permalink: /ai/:path/
  leadership:
    output: true
    permalink: /leadership/:path/
  parenting:
    output: true
    permalink: /parenting/:path/ 