title: My Public Notes
description: Personal notes on AI, Leadership, and Parenting
theme: jekyll-theme-minimal
baseurl: "/my-public-notes"

# Enable GitHub Flavored Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Show excerpts on the home page
show_excerpts: true

# Set the default layout for collections
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default" 