title: My Public Notes
description: Personal notes on AI, Leadership, and Parenting
theme: jekyll-theme-minimal
baseurl: "/my-public-notes"
url: "https://felipepimentel.github.io"

# Theme customization
logo: /assets/img/logo.png

# Enable GitHub Flavored Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Show excerpts on the home page
show_excerpts: true

# Set the default layout for collections
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "AI"
    values:
      layout: "default"
      category: "AI"
  -
    scope:
      path: "Liderança"
    values:
      layout: "default"
      category: "Leadership"
  -
    scope:
      path: "Parentalidade"
    values:
      layout: "default"
      category: "Parenting" 