source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-remote-theme"
gem "just-the-docs", "0.4.0.rc4"
gem "webrick", "~> 1.7"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
end 