name: Build and Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: './docs'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      
      - name: Prepare site files
        run: |
          echo "Preparing site files..."
          
          # Ensure .nojekyll exists
          touch docs/.nojekyll
          
          # Create necessary directories
          mkdir -p docs/assets/{css,js,img}
          
          # Create simple Gemfile if not exists
          if [ ! -f "docs/Gemfile" ]; then
            cat > docs/Gemfile << 'EOF'
source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "webrick", "~> 1.7"
EOF
          fi

          echo "Site files prepared"

      - name: Build site
        working-directory: ./docs
        run: |
          echo "Building Jekyll site..."
          bundle install
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 